---
title: "Titanic"
output: html_document
date: "2025-03-24"
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(data.table)
library(ggplot2)
library(scales)
library(grid)
library(vcd)
```


## Titanic Dataset Analysis
 
```{r, eval = TRUE, include = FALSE}
full = read.csv('titanic.csv')
str(full)
```
```{r, include = FALSE}
full = read.csv('titanic.csv')
str(full)
dim(full)
```

```{r, include = FALSE}

lapply(full, function(x) length(unique(x)))
```
```{r, include = FALSE}
lapply(full, function(x) sum(is.na(x)))
```

```{r, include = FALSE}
full = full %>%
  mutate(Age = ifelse(is.na(Age), mean(full$Age, na.rm = T), Age),
         'Age Group' = case_when(Age < 13 ~ "Age.0012",
                                Age >= 13 & Age < 18 ~ "Age.1317",
                                Age >= 18 & Age < 60 ~ "Age.1859",
                                Age > 60 ~ "Age.60Ov"))
head(full)
```

```{r, include = FALSE}
full$Embarked = replace(full$Embarked, which(is.na(full$Embarked)), 's')
full
```

```{r, include = FALSE}
full$FamilySize = 1 + full$SibSp + full$Parch
full
```

```{r, include = FALSE}
full$FamilySized[full$FamilySize == 1] = "Single"
full$FamilySized[full$FamilySize < 5 & full$FamilySize  >= 2] = "Small"
full$FamilySized[full$FamilySize >= 5] = "Big"
full$FamilySized = as.factor(full$FamilySized)
```

```{r, include = FALSE}
ticket.unique = rep(0, nrow(full))
tickets = unique(full$Ticket)

for(i in 1:length(tickets)) {
  current.ticket = tickets[i]
  party.index = which(full$Ticket == current.ticket)
  for(k in 1:length(party.index)) {
    ticket.unique[party.index[k]] = length(party.index)
  }
}

full$ticket.unique = ticket.unique
full
```
```{r, include = FALSE}
full$ticketSize[full$ticket.unique == 1] = "Single"
full$ticketSize[full$ticket.unique < 5 & full$ticket.unique  >= 2] = "Small"
full$ticketSize[full$ticket.unique >= 5] = "Big"
```


```{r, include = FALSE}
full = full %>%
  mutate(Survived = case_when(Survived == 1 ~ "Yes",
                              Survived == 0 ~ "No"))
```


```{r}
crude_summary = full %>%
  select(PassengerId, Survived) %>%
  group_by(Survived) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
crude_summary
```

```{r}
crude_survrate = crude_summary$freq[crude_summary$Survived == "Yes"]
crude_survrate
```


```{r}
ggplot(full, aes(Pclass, fill = Survived)) + geom_bar(position = "Fill") + scale_y_continuous(label = percent) + ylab("Survival Rate") +
  ggtitle("Survival Rate By Class") + geom_hline(yintercept = crude_survrate, col = "white", size = 2, lty = 2)
```

```{r}
ggplot(full, aes(Sex, fill = Survived)) + geom_bar(position = "Fill") + scale_y_continuous(label = percent) + ylab("Survival Rate") +
  ggtitle("Survival Rate By Sex") + geom_hline(yintercept = crude_survrate, col = "white", size = 2, lty = 2)
```

```{r}
tbl_age = full %>%
  select(Age, Survived) %>%
  group_by(Survived) %>%
  summarise(mean.age = mean(Age, na.rm = T))
tbl_age
```

```{r}
ggplot(full, aes(Age, fill = Survived)) + geom_histogram(aes(y = ..density..), alpha = 0.5) +
  geom_density(alpha = 0.2, aes(color = Survived))
```


```{r}
ggplot(full %>% filter( !is.na(Age)),
       aes(`Age Group`, fill = Survived)) + geom_bar(position = 'fill') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = percent) +
  ylab("Survival Rate") + 
  geom_hline(yintercept = crude_survrate, col = "white", lty = 2, size = 2) +
  ggtitle("Survival Rate by Age Group")
```

```{r}
ggplot(full,
       aes(SibSp, fill = Survived)) + geom_bar(position = 'fill') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = percent) +
  ylab("Survival Rate") + 
  geom_hline(yintercept = crude_survrate, col = "white", lty = 2, size = 2) +
  ggtitle("Survival Rate by SibSp")
```

```{r}
ggplot(full,
       aes(Parch, fill = Survived)) + geom_bar(position = 'fill') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = percent) +
  ylab("Survival Rate") + 
  geom_hline(yintercept = crude_survrate, col = "white", lty = 2, size = 2) +
  ggtitle("Survival Rate by Parch")
```

```{r}
ggplot(full,
       aes(Embarked, fill = Survived)) + geom_bar(position = 'fill') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = percent) +
  ylab("Survival Rate") + 
  geom_hline(yintercept = crude_survrate, col = "white", lty = 2, size = 2) +
  ggtitle("Survival Rate by Embarked")
```

```{r}
ggplot(full %>% na.omit,
       aes(`FamilySize`, fill = Survived)) + geom_bar(position = 'fill') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = percent) +
  ylab("Survival Rate") + 
  geom_hline(yintercept = crude_survrate, col = "white", lty = 2, size = 2) +
  ggtitle("Survival Rate by Family Group")
```

```{r}
ggplot(full,
       aes(Pclass, fill = Survived)) + geom_bar(position = 'stack') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = comma) +
  ylab("Passengers") + 
  ggtitle("Survival Rate by Class")
```

```{r}
ggplot(full,
       aes(Sex, fill = Survived)) + geom_bar(position = 'stack') + 
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = comma) +
  ylab("Passengers") + 
  ggtitle("Survival Rate by Sex")
```

```{r}
ggplot(full,
       aes(Age, fill = Survived)) + geom_histogram(aes(y = ..count..), alpha = 0.5) + 
  geom_vline(data = tbl_age, aes(xintercept = mean.age, colour = Survived), lty=2, size=1) +
  scale_fill_brewer(palette = "Set1") +
  scale_colour_brewer(palette = "Set1") +
  scale_y_continuous(labels = comma) +
  ylab("Density") + 
  ggtitle("Survival Rate by Sex")
```